exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]
source_roots = ["src"]

[[modules ]]
path = "social_auth"
depends_on = [{path = "sentry", deprecated = true}]

[[modules ]]
path = "flagpole"
depends_on = []

[[modules ]]
path = "bitfield"
depends_on = []

[[modules ]]
path = "sudo"
depends_on = []

[[modules ]]
path = "sentry"
depends_on = ["flagpole", "social_auth", "sentry_plugins", "sudo", "bitfield", "django_picklefield"]

[[modules ]]
path = "django_picklefield"
depends_on = []

[[modules ]]
path = "sentry_plugins"
depends_on = [{path = "sentry", deprecated = true}]


[[interfaces]]
expose = [
    ".*utils.*",
    ".*integrations.*",
    ".*utils.*",
    ".*services.*",
]

[[interfaces]]
expose = [
    "django_picklefield",
]
from = ["django_picklefield"]

[[interfaces]]
expose = [
    ".*plugin.*",
]
from = ["sentry_plugins"]


[[interfaces]]
expose = [
    ".*Bit.*",
    ".*bit.*",
]
from = ["bitfield"]

[[interfaces]]
expose = [
    "backends.BaseAuth",
]
from = ["social_auth"]

[[interfaces]]
expose = [
    "evaluation.*",
    "conditions.*"
]
from = ["flagpole"]

[[interfaces]]
expose = [
    ".*",
]
from = ["sudo"]
