name: ci


permissions:
  contents: read
  pull-requests: write
  checks: write

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  report:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          check-latest: true


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tach>=0.27.2
      - name: tach report upload
        env:
          GAUGE_API_KEY: ${{ secrets.GAUGE_API_KEY }}
          GAUGE_API_BASE_URL: ${{ secrets.GAUGE_API_BASE_URL }}
        run: tach upload
      - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         tach check |& reviewdog -efm="[FAIL] %f:%l: %m" -name="tach" -reporter=github-pr-check  -diff="git diff FETCH_HEAD"
