name: ci

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  report:
    runs-on: ubuntu-22.04
    environment: tach-demo
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          check-latest: true


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tach==0.16.5
      - name: tach report upload
        env:
          GAUGE_API_KEY: ${{ secrets.GAUGE_API_KEY }}
          GAUGE_API_BASE_URL: ${{ secrets.GAUGE_API_BASE_URL }}
        run: |
          cd src
#          tach upload
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
