name: ci

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          check-latest: true


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tach==0.16.3
      - name: tach report upload
        run: |
          cd src
          tach upload